
package br.univel.artefatos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecuredWebServiceService", targetNamespace = "http://univel.br/", wsdlLocation = "http://localhost:8080/jserver-app/SecuredWebService?wsdl")
public class SecuredWebServiceService
    extends Service
{

    private final static URL SECUREDWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SECUREDWEBSERVICESERVICE_EXCEPTION;
    private final static QName SECUREDWEBSERVICESERVICE_QNAME = new QName("http://univel.br/", "SecuredWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jserver-app/SecuredWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECUREDWEBSERVICESERVICE_WSDL_LOCATION = url;
        SECUREDWEBSERVICESERVICE_EXCEPTION = e;
    }

    public SecuredWebServiceService() {
        super(__getWsdlLocation(), SECUREDWEBSERVICESERVICE_QNAME);
    }

    public SecuredWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECUREDWEBSERVICESERVICE_QNAME, features);
    }

    public SecuredWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SECUREDWEBSERVICESERVICE_QNAME);
    }

    public SecuredWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECUREDWEBSERVICESERVICE_QNAME, features);
    }

    public SecuredWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecuredWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecuredWebService
     */
    @WebEndpoint(name = "SecuredWebServicePort")
    public SecuredWebService getSecuredWebServicePort() {
        return super.getPort(new QName("http://univel.br/", "SecuredWebServicePort"), SecuredWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecuredWebService
     */
    @WebEndpoint(name = "SecuredWebServicePort")
    public SecuredWebService getSecuredWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://univel.br/", "SecuredWebServicePort"), SecuredWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECUREDWEBSERVICESERVICE_EXCEPTION!= null) {
            throw SECUREDWEBSERVICESERVICE_EXCEPTION;
        }
        return SECUREDWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
